freeze: true
project:
  type: book

book:
  title: "Best Practices on the DNAnexus Platform"
  author: "Ted Laderas"
  date: "1/23/2023"
  chapters:
    - "index.qmd"
    - "10-object-based-file-systems.qmd"
    - "12-project_management.qmd"
    - "13-spark-on-dnanexus.qmd"
    - "dx_extract_dataset_R.ipynb"
#    - "dx_extract_dataset_python.ipynb"
#    - "14-hail-on-dnanexus.qmd"
    - "01-Hail-Skills.ipynb"
    - "02-gwas.ipynb"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt



