---
title: "UK Biobank Cheatsheet"
---

## Learning Path: Clinician

Goals: 

- Assess and validate cohort definitions built within Cohort Browser. 
- Compare and visualize distributions in phenotype covariates between cohorts

|Resource|Type|Why it's Useful|
|--------|----|---------------|
|Cloud Computing For Scientists|Webinar|Introduction to Cloud Computing concepts|
|Bash for Bioinformatics: Cloud Computing|Book Chapter|Learn essential bash skills|
|UKB Overview|Webinar|Understand the basic UKB RAP project structure and work with it|
|Intro to Cohort Browser|Tutorial|Learn how to access UKB data through Cohort Browser and build cohorts|

## Learning Path: Epidemiologist/Statistician

Goals: 

- Assess cohorts and conduct statistical analysis on Phenotype Data. 
- Build cohorts with cohort browser for assessment by clinician and further validation. 
- Explore and analyze phenotypic data in a JupyterLab notebook with R, Python, or Stata. 
- Use RStudio effectively on the platform to explore and analyze phenotypic data.

|Resource|Type|Why it's Useful|
|--------|----|---------------|
|Bash for Bioinformatics: Cloud Computing|Book Chapter||
|JupyterLab Part 1|Webinar||
|JupyterLab Part 2|Webinar||
|Analyzing Data with RStudio|Webinar||


## Learning Path: Bioinformatician

Goals: 

- Adapt HPC skills for running cloud-based jobs. 
- Leverage genomic data in downstream analysis. 
- Run existing workflows on data in UKB RAP storage in a project. 
- Conduct GWAS analysis in Hail or Regenie given the stored genotype data. 

|Resource|Type|Why it's Useful|
|--------|----|---------------|
|Cloud Computing For HPC Users|Webinar||
|UKB Overview|Webinar||
|Bash for Bioinformatics|Online Book|Contains recipes for automating processes on UKB RAP using bash and the CLI|
|Cloud Computing for HPC Users|Webinar|Translate HPC skills to the UKB RAP|
|Running Apps on UKB RAP|Webinar|Details how to run common bioinformatics apps (Plink, samtools) using the Swiss Army Knife app|
|Building Apps on UKB RAP|Webinar|Run other executables (such as GATK) by building a UKB RAP compatible version|
|GWAS Guide|Online Guide|Using the already built Regenie app on the platform for GWAS|
|GWAS using Swiss Army Knife and the dx-toolkit|Online Guide|Preparing Geno/Pheno Data on RAP|


## Learning Path: Machine Learning Engineer

Goals: Integrate already processed genotype/phenotype data to build and deploy statistical or machine learning models.

|Resource|Type|Why it's Useful For You|
|--------|----|---------------|
|Cloud Computing For HPC Users|Webinar|Translate HPC to UKB RAP|
|||


## Learning Path: Project Administrator

Goals: 

- Set up a UKB Project for your organization. 
- Dispense data into your project
- Manage members in your project. 
- Redispense data into your project when data is refreshed. 

|Resource|Type|Why it's useful|
|--------|----|---------------|
|Cloud Computing For Scientists|Webinar|Learn basic cloud concepts to work effectively on UKB RAP|
|UKB RAP Doc: Accessing the Research Analysis Platform|Documentation|Setting up your access to RAP|
|UKB RAP Documentation: Creating a Project|Documentation||
|UKB RAP Doc: Updating Dispensed Data|Documentation||
|UKB RAP Doc: UK Biobank data on RAP|Documentation||
|Bash for Bioinformatics: Cloud Computing|Book Chapter||
|UKB Overview|Webinar||
